apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # "rootpassword" у Base64
  MYSQL_DATABASE: YXBwX2Ri              # "app_db" у Base64
  MYSQL_USER: YXBwX3VzZXI=              # "app_user" у Base64
  MYSQL_PASSWORD: YXBwX3Bhc3N3b3Jk      # "app_password" у Base64