Vagrant.configure("2") do |config|
  # Загальні налаштування
  config.vm.box = "ubuntu/focal64"

  # ===== DB_VM =====
  config.vm.define "db" do |db|
    db.vm.hostname = "db-vm"
    db.vm.network "private_network", ip: 
"192.168.56.10"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    db.vm.provision "shell", path: 
"provision_db.sh"
  end

  # ===== APP_VM =====
  config.vm.define "app" do |app|
    app.vm.hostname = "app-vm"
    app.vm.network "forwarded_port", guest: 8080, 
host: 8080
    app.vm.network "private_network", ip: 
"192.168.56.11"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    app.vm.provision "shell", path: 
"provision_app.sh"
  end
end

