groups:
  - name: monitoring_alerts
    rules:
      
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{mountpoint="/host"} / node_filesystem_size_bytes{mountpoint="/host"}) * 100 < 15
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Низький рівень вільного місця на диску"
          description: "На диску залишилося менше 15% вільного простору (поточне значення: {{ $value | humanize }}%)."

      
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Високе завантаження CPU"
          description: "CPU використовується більше ніж на 80% протягом останніх 2 хвилин (поточне значення: {{ $value | humanize }}%)."

      
      - alert: TargetDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Ціль (Target) недоступна"
          description: "Таргет {{ $labels.job }} (інстанс {{ $labels.instance }}) недоступний більше 30 секунд."